"""M5: scaling-study scaffold for the multi-host data-parallel step (cheap ladder).

This sweeps device counts 1/2/4/8 and, at each, runs a representative data-parallel jitted step (a small
multi-layer FFN with a value_and_grad, sharded along the mesh `data` axis exactly like the real train_step's
batch) through the G6 profiler. It reports per-step device time + MFU/roofline, weak-scaling the global batch so
that *ideal* hardware would hold step time constant as devices grow.

IMPORTANT (flagged): on simulated CPU devices these "devices" share the same physical cores, so the absolute
times and the scaling curve are NOT representative of real accelerators — this validates that the sharded code
PATH builds and runs at each scale and produces a measurement, i.e. the harness you'd run on a real slice. Real
throughput / interconnect scaling is hardware-gated.

Usage:
  python scripts/scaling_study.py                 # sweep 1,2,4,8 and write FINDINGS.md
  python scripts/scaling_study.py --probe         # measure once at the current XLA device count (internal)
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys

_DEVICE_COUNTS = (1, 2, 4, 8)
_PER_DEVICE_BATCH = 8
_DIM = 1024
_LAYERS = 4


def _probe() -> dict:
    """Measure one data-parallel step at the current jax.device_count(). Prints JSON."""
    import jax
    import jax.numpy as jnp
    import numpy as np

    from openpi.training import profiling, sharding

    d = jax.device_count()
    mesh = sharding.make_mesh(num_fsdp_devices=1)  # (data=d, fsdp=1) — pure data parallel
    batch_sh = jax.sharding.NamedSharding(mesh, jax.sharding.PartitionSpec(sharding.DATA_AXIS, None))
    repl = jax.sharding.NamedSharding(mesh, jax.sharding.PartitionSpec())

    global_b = _PER_DEVICE_BATCH * d  # weak scaling: per-device work is constant
    rng = np.random.default_rng(0)
    batch = jax.device_put(rng.standard_normal((global_b, _DIM), dtype=np.float32), batch_sh)
    params = [
        jax.device_put(rng.standard_normal((_DIM, _DIM), dtype=np.float32) / _DIM**0.5, repl)
        for _ in range(_LAYERS)
    ]

    def loss_fn(params, batch):
        x = batch
        for w in params:
            x = jax.nn.gelu(x @ w)
        return jnp.mean(x**2)

    step = jax.jit(
        jax.value_and_grad(loss_fn),
        in_shardings=(repl, batch_sh),
        out_shardings=(repl, repl),
    )
    compiled = step.lower(params, batch).compile()
    peak = float(os.environ["SHARDER_PEAK_FLOPS"]) if os.environ.get("SHARDER_PEAK_FLOPS") else None
    report = profiling.profile_step(
        lambda: step(params, batch), compiled, peak_flops=peak, warmup=3, iters=20
    )
    return {
        "devices": d,
        "global_batch": global_b,
        "median_step_ms": report.step_time.median_s * 1e3,
        "achieved_tflops": report.achieved_flops_per_s / 1e12,
        "mfu": report.mfu,
        "bound": report.bound,
    }


def _sweep() -> int:
    rows = []
    for dc in _DEVICE_COUNTS:
        env = {**os.environ, "XLA_FLAGS": f"--xla_force_host_platform_device_count={dc}"}
        # Ensure the child can import openpi when run from a source checkout.
        env.setdefault("PYTHONPATH", os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "src"))
        res = subprocess.run(
            [sys.executable, os.path.abspath(__file__), "--probe"],
            env=env,
            capture_output=True,
            text=True,
            timeout=300,
        )
        if res.returncode != 0:
            print(f"[scaling] device_count={dc} FAILED:\n{res.stderr}", file=sys.stderr)
            return 1
        rows.append(json.loads(res.stdout.strip().splitlines()[-1]))
        print(f"[scaling] {rows[-1]}")

    _write_findings(rows)
    return 0


def _write_findings(rows: list[dict]) -> None:
    base_ms = rows[0]["median_step_ms"]
    lines = [
        "# Scaling study (cheap ladder) — FINDINGS",
        "",
        "Representative data-parallel step (4-layer FFN + value_and_grad), batch sharded along the mesh `data`",
        "axis, **weak-scaled** (global batch = 8 x devices). Generated by `scripts/scaling_study.py`.",
        "",
        "> ⚠️ Simulated CPU devices share the same physical cores, so absolute time and the scaling curve are NOT",
        "> representative of real accelerators. This shows the sharded code PATH runs at each scale and the harness",
        "> produces measurements. Real throughput + interconnect scaling are HARDWARE-GATED.",
        "",
        "| devices | global batch | median step (ms) | achieved TFLOP/s | MFU | roofline | step/step(1x) |",
        "|--------:|-------------:|-----------------:|-----------------:|:---:|:--------:|--------------:|",
    ]
    for r in rows:
        mfu = "n/a" if r["mfu"] is None else f"{r['mfu'] * 100:.1f}%"
        lines.append(
            f"| {r['devices']} | {r['global_batch']} | {r['median_step_ms']:.2f} | "
            f"{r['achieved_tflops']:.3f} | {mfu} | {r['bound'] or 'n/a'} | "
            f"{r['median_step_ms'] / base_ms:.2f}x |"
        )
    lines += [
        "",
        "Ideal weak scaling on real hardware ⇒ `step/step(1x)` stays ~1.00 as devices grow (constant step time,",
        "throughput scales with devices). Deviations on CPU here are the shared-core artifact noted above.",
        "",
    ]
    with open("FINDINGS.md", "w") as f:
        f.write("\n".join(lines))
    print("[scaling] wrote FINDINGS.md")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--probe", action="store_true", help="measure once at current device count (internal)")
    args = parser.parse_args()
    if args.probe:
        print(json.dumps(_probe()))
        return 0
    return _sweep()


if __name__ == "__main__":
    sys.exit(main())
